workflow:
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "master"
       when: always
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
       when: always
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never

stages:
  - build
  - test

.binary_latest:
  image: kitware/paraview_org-plugin-devel:latest
  variables:
    PARAVIEW_VERSION: "latest"
  rules:
    - if: $DISABLE_LATEST == "True"
      when: never
    - when: on_success

.binary_5110:
  image: kitware/paraview_org-plugin-devel:5.11.0
  variables:
    PARAVIEW_VERSION: "5.11.0"
  rules:
    - if: $DISABLE_V511 == "True"
      when: never
    - when: on_success

.binary_5101:
  image: kitware/paraview_org-plugin-devel:5.10.1
  variables:
    PARAVIEW_VERSION: "5.10.1"
  rules:
    - if: $DISABLE_V510 == "True"
      when: never
    - when: on_success

.build_binary_compatible:
  stage: build
  before_script:
    - source /opt/rh/devtoolset-7/enable
  script:
      # This is needed because the build of ParaView use some absolute path
    - ln -s /paraview/gitlab-kitware-sciviz-ci/ /builds/gitlab-kitware-sciviz-ci
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/builds/gitlab-kitware-sciviz-ci/build/install/ -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux-x86_64
    - paraview
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/
  rules:
    - if: $DISABLE_BINARY == "True"
      when: never
    - when: on_success

.build_plugin:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/paraview/install/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --parallel 2
  tags:
    - docker
    - linux-x86_64
    - paraview
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

.test_plugin:
  stage: test
  script:
    - cd build
    - xvfb-run ctest -j 2 --output-on-failure || xvfb-run ctest -j 1 --rerun-failed -VV
  tags:
    - docker
    - linux-x86_64
    - paraview

.latest:
  image: kitware/paraview-for-ci:latest
  variables:
    PARAVIEW_VERSION: "latest"
  rules:
    - if: $DISABLE_LATEST == "True"
      when: never
    - when: on_success

.v5110:
  image: kitware/paraview-for-ci:v5.11.0
  variables:
    PARAVIEW_VERSION: "5.11.0"
  rules:
    - if: $DISABLE_V511 == "True"
      when: never
    - when: on_success

.v5101:
  image: kitware/paraview-for-ci:v5.10.1
  variables:
    PARAVIEW_VERSION: "5.10.1"
  rules:
    - if: $DISABLE_V510 == "True"
      when: never
    - when: on_success

.v591:
  image: kitware/paraview-for-ci:v5.9.1
  variables:
    PARAVIEW_VERSION: "5.9.1"
  rules:
    - if: $DISABLE_V59 == "True"
      when: never
    - when: on_success

.v581:
  image: kitware/paraview-for-ci:v5.8.1
  variables:
    PARAVIEW_VERSION: "5.8.1"
  rules:
    - if: $DISABLE_V58 == "True"
      when: never
    - when: on_success

build_binary_compatible_latest:
  extends:
    - .build_binary_compatible
    - .binary_latest

build_binary_compatible_5.11.0:
  extends:
    - .build_binary_compatible
    - .binary_5110

build_binary_compatible_5.10.1:
  extends:
    - .build_binary_compatible
    - .binary_5101

build_plugin_latest:
  extends:
    - .build_plugin
    - .latest

test_plugin_latest:
  extends:
    - .test_plugin
    - .latest
  dependencies:
    - build_plugin_latest
  needs:
    - build_plugin_latest

build_plugin_v5.11.0:
  extends:
    - .build_plugin
    - .v5110

test_plugin_v5.11.0:
  extends:
    - .test_plugin
    - .v5110
  dependencies:
    - build_plugin_v5.11.0
  needs:
    - build_plugin_v5.11.0

build_plugin_v5.10.1:
  extends:
    - .build_plugin
    - .v5101

test_plugin_v5.10.1:
  extends:
    - .test_plugin
    - .v5101
  dependencies:
    - build_plugin_v5.10.1
  needs:
    - build_plugin_v5.10.1

build_plugin_v5.9.1:
  extends:
    - .build_plugin
    - .v591

test_plugin_v5.9.1:
  extends:
    - .test_plugin
    - .v591
  dependencies:
    - build_plugin_v5.9.1
  needs:
    - build_plugin_v5.9.1

build_plugin_v5.8.1:
  extends:
    - .build_plugin
    - .v581

test_plugin_v5.8.1:
  extends:
    - .test_plugin
    - .v581
  dependencies:
    - build_plugin_v5.8.1
  needs:
    - build_plugin_v5.8.1
