workflow:
   rules:
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "master"
       when: always
     - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
       when: always
     - if: $CI_MERGE_REQUEST_ID
       when: always
     - when: never

stages:
  - build
  - test

include:
  - local: .gitlab/common.yml
  - local: .gitlab/latest.yml
  - local: .gitlab/5.13.yml
  - local: .gitlab/5.12.yml
  - local: .gitlab/5.11.yml
  - local: .gitlab/5.10.yml
  - local: .gitlab/5.9.yml
  - local: .gitlab/5.8.yml
