stages:
  - build
  - test

build-plugin-release:
  image: kitware/paraview_org-plugin-devel:5.10.1
  stage: build
  script:
      # This is needed because the build of ParaView use some absolute path
    - ln -s /paraview/gitlab-kitware-sciviz-ci/ /builds/gitlab-kitware-sciviz-ci
    - mkdir -p build
    - cd build
    - cmake -DParaView_DIR=/builds/gitlab-kitware-sciviz-ci/build/install/lib/cmake/paraview-5.10/ ..
    - cmake --build . --config Release --parallel 2
  tags: 
    - docker
    - linux
    - paraview
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

build-plugin:
  image: kitware/paraview-for-ci:v5.10.1
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DParaView_DIR=/paraview_build -DBUILD_TESTING=ON ..
    - cmake --build . --config Release --parallel 2
  tags: 
    - docker
    - linux
    - paraview
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/

test-plugin:
  image: kitware/paraview-for-ci:v5.10.1
  stage: test
  script:
    - cd build
    - ctest -C Release -j 2 --output-on-failure || ctest -C Release -j 1 --rerun-failed -VV
  tags: 
    - docker
    - linux
    - paraview
  dependencies:
    - build-plugin
  needs:
    - build-plugin
