image: $CI_REGISTRY/visualization/paraview-image-builder/paraview_master

stages:
  - build
  - test

build-plugin:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DParaView_DIR=/paraview_build/bin/paraview -DBUILD_TESTING=ON ..
    - cmake --build . --config Release --parallel 2
  tags: 
    - docker
  artifacts:
    expire_in: 1h
    when: always
    paths:
      - build/


test-plugin:
  stage: test
  needs: ['build-plugin']
  script:
    - cd build
    - ctest
  tags: 
    - docker
  dependencies:
    - build-plugin
